name: build-to-ecr
run-name: ${{github.actor}} is Running a Build to ECR
on:
  push:
  workflow_dispatch:
jobs:
  build-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Change Gradle Wrapper Permissions
        run: chmod +x ./gradlew
      - name: Run the Gradle Build Task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
     # - name: Build the Docker Image
     #   run: docker build . --file Dockerfile --tag periodictable:latest
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push Docker Image to AWS ECR
        run: |
          docker build . --file Dockerfile --tag periodictable:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/github-actions-demo:periodictable